version: "3.8"
services:
    jsartoolkit5:
        image: 76527413/jsartoolkit5
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./default.conf:/etc/nginx/conf.d/default.conf
            - ./html/demo.html:/usr/share/nginx/html/demo.html
